### ISSUE TITLE
压缩后的视频转base64字符串  无法播放

### ISSUE THREAD

**Issue by jiasijiedajidali** [yellowcath/VideoProcessor#47]
视频压缩后  把压缩过后的文件转成base64字符串  在转成文件无法播放 @yellowcath

**Comment by dongdianyi** [comment]
老哥有解决方案吗，我也遇到相同问题

**Comment by ygdhsb1995** [comment]
我转了可以啊

**Comment by dongdianyi** [comment]
电脑播放不了



---原始邮件---
发件人: "ygdhsb1995"<notifications@github.com&gt;
发送时间: 2020年7月27日(周一) 下午3:39
收件人: "yellowcath/VideoProcessor"<VideoProcessor@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"dongdianyi"<411913512@qq.com&gt;;
主题: Re: [yellowcath/VideoProcessor] 压缩后的视频转base64字符串  无法播放 (#47)




 
我转了可以啊

**Comment by ygdhsb1995** [comment]
> 电脑播放不了
> […](#)
> ---原始邮件--- 发件人: "ygdhsb1995"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 下午3:39 收件人: "yellowcath/VideoProcessor"<VideoProcessor@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"dongdianyi"<411913512@qq.com&gt;; 主题: Re: [yellowcath/VideoProcessor] 压缩后的视频转base64字符串 无法播放 (#47) 我转了可以啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

可以播放啊，也都是android自带的base64方法，加密解码

**Comment by dongdianyi** [comment]
电脑可以播放？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ygdhsb1995"<notifications@github.com&gt;; 
发送时间: 2020年7月27日(星期一) 下午3:44
收件人: "yellowcath/VideoProcessor"<VideoProcessor@noreply.github.com&gt;; 
抄送: "."<411913512@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yellowcath/VideoProcessor] 压缩后的视频转base64字符串  无法播放 (#47)





  
电脑播放不了
 …
 ---原始邮件--- 发件人: "ygdhsb1995"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 下午3:39 收件人: "yellowcath/VideoProcessor"<VideoProcessor@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"dongdianyi"<411913512@qq.com&gt;; 主题: Re: [yellowcath/VideoProcessor] 压缩后的视频转base64字符串 无法播放 (#47) 我转了可以啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可以播放啊，也都是android自带的base64方法，加密解码

**Comment by ygdhsb1995** [comment]
> 电脑可以播放？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ygdhsb1995"<notifications@github.com&gt;; 发送时间: 2020年7月27日(星期一) 下午3:44 收件人: "yellowcath/VideoProcessor"<VideoProcessor@noreply.github.com&gt;; 抄送: "."<411913512@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [yellowcath/VideoProcessor] 压缩后的视频转base64字符串 无法播放 (#47) 电脑播放不了 … ---原始邮件--- 发件人: "ygdhsb1995"<notifications@github.com&gt; 发送时间: 2020年7月27日(周一) 下午3:39 收件人: "yellowcath/VideoProcessor"<VideoProcessor@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"dongdianyi"<411913512@qq.com&gt;; 主题: Re: [yellowcath/VideoProcessor] 压缩后的视频转base64字符串 无法播放 (#47) 我转了可以啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 可以播放啊，也都是android自带的base64方法，加密解码 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

可以，安卓手机和微软系统电脑都可以

**Comment by jiasijiedajidali** [comment]
> 老哥有解决方案吗，我也遇到相同问题

可以播放   在视频处理完成后  加个500毫秒左右的延时  在去转base64字符串 就可以了
